name: stephanie
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_svg: ^1.0.0
  flutter_bloc: ^8.0.1
  lottie: ^1.2.1
  url_launcher: ^6.0.12
  font_awesome_flutter: ^9.2.0
  image_picker: ^0.8.4+5
  gallery_saver: ^2.3.2
  file_picker: ^4.3.3
  flutter_stegify: ^0.2.0
  path_provider: ^2.0.8
  open_filex: ^3.4.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/drawkit/
    - assets/logo/
    - assets/lottie/

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#303030"
  icon_background_color: "#FFFFFF"
  icon_background_color_dark: "#303030"
  image: assets/logo/stephanie_transparent_logo.png
  image_dark: assets/logo/stephanie_transparent_logo.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  web: false
  android_12:
    image: assets/logo/stephanie_transparent_logo.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#303030"
    color: "#FFFFFF"
    color_dark: "#303030"

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo/stephanie_transparent_logo.png
  image_path_ios: assets/logo/stephanie_logo.png
  adaptive_icon_background: "#FFFFFF"